### ISSUE TITLE
Add code climate [optional]

### ISSUE THREAD

**Issue by audip** [thrawn01/args#3]
- Another cool integration on many repos is code climate, https://codeclimate.com/, similar to [![Code Climate](https://codeclimate.com/github/audip/my-site/badges/gpa.svg)](https://codeclimate.com/github/audip/my-site)

**Comment by thrawn01** [comment]
Thanks for the suggestion, I've added it.

**Comment by audip** [comment]
Fixme validator of code climate fails, too many TODO have been found. Fixing that, will then allow duplication and radon processes to run.
